import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Interview Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-full w-full justify-center bg-gray-200">
        <div className="w-full max-w-7xl bg-gray-300 px-5 py-20 md:px-10">
          <h1 className="mb-4 text-3xl font-bold">Interview Template</h1>
          <p>
            This interview template is designed to test your skills on the
            following frontend technologies:
          </p>
          <ul className="mt-4 list-disc pl-4">
            <li>React.js</li>
            <li>Next.js</li>
            <li>Typescript</li>
            <li>Tailwind CSS</li>
          </ul>
        </div>
      </div>
    </>
  );
}
